import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "#ddb7ff",
          container: "#b76dff",
          "on-primary": "#490080",
          "on-container": "#400071",
          fixed: "#f0dbff",
          "fixed-dim": "#ddb7ff",
        },
        secondary: {
          DEFAULT: "#c8c6c8",
          container: "#474649",
          "on-secondary": "#313032",
          "on-container": "#b7b4b7",
        },
        tertiary: {
          DEFAULT: "#4cd7f6",
          container: "#009eb9",
          "on-tertiary": "#003640",
          "on-container": "#002f38",
          fixed: "#acedff",
          "fixed-dim": "#4cd7f6",
        },
        surface: {
          DEFAULT: "#131315",
          dim: "#131315",
          bright: "#39393b",
          variant: "#353437",
          tint: "#ddb7ff",
          "container-lowest": "#0e0e10",
          "container-low": "#1c1b1d",
          container: "#201f22",
          "container-high": "#2a2a2c",
          "container-highest": "#353437",
        },
        background: "#131315",
        "on-background": "#e5e1e4",
        "on-surface": "#e5e1e4",
        "on-surface-variant": "#cfc2d6",
        outline: {
          DEFAULT: "#988d9f",
          variant: "#4d4354",
        },
        error: {
          DEFAULT: "#ffb4ab",
          container: "#93000a",
          "on-error": "#690005",
          "on-container": "#ffdad6",
        },
        inverse: {
          surface: "#e5e1e4",
          "on-surface": "#313032",
          primary: "#842bd2",
        },
      },
      borderRadius: {
        none: "0px",
        sm: "0px",
        DEFAULT: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        "3xl": "0px",
        full: "9999px",
      },
      fontFamily: {
        headline: ['"Space Grotesk"', "sans-serif"],
        label: ['"Inter"', "sans-serif"],
        body: ['"Inter"', "sans-serif"],
        mono: ['"JetBrains Mono"', '"Space Grotesk"', "monospace"],
      },
      fontSize: {
        "display-lg": ["3.5625rem", { lineHeight: "4rem", letterSpacing: "-0.015em", fontWeight: "400" }],
        "display-md": ["2.8125rem", { lineHeight: "3.25rem", letterSpacing: "-0.01em", fontWeight: "400" }],
        "display-sm": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "0", fontWeight: "400" }],
        "headline-lg": ["2rem", { lineHeight: "2.5rem", letterSpacing: "0", fontWeight: "600" }],
        "headline-md": ["1.75rem", { lineHeight: "2.25rem", letterSpacing: "0", fontWeight: "600" }],
        "headline-sm": ["1.5rem", { lineHeight: "2rem", letterSpacing: "0", fontWeight: "600" }],
        "title-lg": ["1.375rem", { lineHeight: "1.75rem", letterSpacing: "0", fontWeight: "500" }],
        "title-md": ["1rem", { lineHeight: "1.5rem", letterSpacing: "0.009em", fontWeight: "500" }],
        "title-sm": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0.007em", fontWeight: "500" }],
        "body-lg": ["1rem", { lineHeight: "1.5rem", letterSpacing: "0.009em", fontWeight: "400" }],
        "body-md": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0.016em", fontWeight: "400" }],
        "body-sm": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.025em", fontWeight: "400" }],
        "label-lg": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0.007em", fontWeight: "500" }],
        "label-md": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.031em", fontWeight: "500" }],
        "label-sm": ["0.6875rem", { lineHeight: "1rem", letterSpacing: "0.031em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
